name: Setup nupm
description: Install and setup nupm environment

inputs:
  nu_version:
    description: "A valid semver, such as 'M.m.p', '*' or 'nightly'."
    required: true
    default: "*"
  nupm_revision:
    description: "A commit hash, branch name or tag to checkout before installing Nupm."
    required: true
    default: "*"
  nupm_clone_path:
    description: "The path where Nupm will be cloned"
    required: true
    default: "/tmp/nupm"
  nupm_path:
    description: "The path where Nupm will be installed"
    required: true
    default: "~/.local/share/nupm"

outputs:
  nupm_path:
    value: ${{ steps.set-output.outputs.nupm-path }}
    description: "The path to the installed nupm (can be `use`d directly) "

runs:
  using: composite
  steps:
    - uses: hustcer/setup-nu@v3.8
      with:
        version: ${{ inputs.nu_version }}

    - name: Show Nushell Version
      shell: nu {0}
      run: version

    - name: Pull down Nupm
      shell: nu {0}
      run: |
        git clone https://github.com/nushell/nupm ${{ inputs.nupm_clone_path }}
        git -C ${{ inputs.nupm_clone_path }} checkout ${{ inputs.nupm_revision }}

    - name: Install nupm
      shell: nu {0}
      id: set-output
      run: |
        use ${{ inputs.nupm_clone_path }}/nupm
        let nupm_home = "${{ inputs.nupm_path }}" | path expand
        with-env {NUPM_HOME: $nupm_home} {
          mkdir $env.NUPM_HOME
          nupm install --force --path "${{ inputs.nupm_clone_path }}"
        }

        'nupm-path="${{ inputs.nupm_path }}/modules/nupm"' | save --append $env.GITHUB_OUTPUT

